// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx5w9SRJu9seG5mTubwxHXekF4aiM01g8',
    appId: '1:113628527943:web:f0d4370aeecfe6fe67a062',
    messagingSenderId: '113628527943',
    projectId: 'homemaker-firebase',
    authDomain: 'homemaker-firebase.firebaseapp.com',
    storageBucket: 'homemaker-firebase.appspot.com',
    measurementId: 'G-VNX9DEW5DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-3_N0uDbQAQNJK4Y1-94G96S85EZKv8',
    appId: '1:113628527943:android:f8d79fdb090c04d767a062',
    messagingSenderId: '113628527943',
    projectId: 'homemaker-firebase',
    storageBucket: 'homemaker-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-I_TwojSwL8DcvNJq8cmzPa2Ywhqf3gM',
    appId: '1:113628527943:ios:a7b3ba2c76921e7c67a062',
    messagingSenderId: '113628527943',
    projectId: 'homemaker-firebase',
    storageBucket: 'homemaker-firebase.appspot.com',
    iosBundleId: 'com.example.homechefV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-I_TwojSwL8DcvNJq8cmzPa2Ywhqf3gM',
    appId: '1:113628527943:ios:9a80d8c8b05036db67a062',
    messagingSenderId: '113628527943',
    projectId: 'homemaker-firebase',
    storageBucket: 'homemaker-firebase.appspot.com',
    iosBundleId: 'com.example.homechefV3.RunnerTests',
  );
}
